#!/usr/bin/env bash
#
# Copyright (C) 2017-2019 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copy the built Dremio tarball to $WORK/dremio, configure instance ports, start it, bootstrap the
# first user (dremio/dremio123, local test only) and save the auth token to $WORK/token.
#
# Usage: INSTANCE=0 dremio-up.sh [--reuse]
#   --reuse   keep the existing $WORK/dremio copy and its data (restart scenario)
# Env: DREMIO_TARBALL_DIR (default: distribution/server/target/dremio-community-*/dremio-community-*),
#      DREMIO_JAVA_HOME (default ~/jvm/jdk-17.0.9), DREMIO_HEAP_MB / DREMIO_DIRECT_MB (2048),
#      DREMIO_START_TIMEOUT (seconds, default 300)
set -euo pipefail
# shellcheck source=common.sh
. "$(dirname "${BASH_SOURCE[0]}")/common.sh"

require_cmd curl jq ss
ensure_work

reuse=0
[ "${1:-}" = "--reuse" ] && reuse=1

[ -x "$DREMIO_JAVA_HOME/bin/java" ] || die "DREMIO_JAVA_HOME=$DREMIO_JAVA_HOME has no bin/java"

if [ -f "$DREMIO_HOME_DIR/run/dremio.pid" ] && kill -0 "$(cat "$DREMIO_HOME_DIR/run/dremio.pid")" 2>/dev/null; then
  die "Dremio for INSTANCE=$INSTANCE is already running (run dremio-down.sh first)"
fi
require_free_ports "$DREMIO_WEB_PORT" "$DREMIO_CLIENT_PORT" "$DREMIO_FLIGHT_PORT" "$DREMIO_FABRIC_PORT" "$DREMIO_ZK_PORT"

if [ "$reuse" = 1 ] && [ -x "$DREMIO_HOME_DIR/bin/dremio" ]; then
  log "reusing $DREMIO_HOME_DIR"
else
  src="${DREMIO_TARBALL_DIR:-}"
  if [ -z "$src" ]; then
    for d in "$REPO_ROOT"/distribution/server/target/dremio-community-*/dremio-community-*; do
      [ -x "$d/bin/dremio" ] && src="$d"
    done
  fi
  [ -n "$src" ] && [ -x "$src/bin/dremio" ] || die "no Dremio tarball dir found (build distribution/server or set DREMIO_TARBALL_DIR)"
  rm -rf "$DREMIO_HOME_DIR"
  mkdir -p "$DREMIO_HOME_DIR"
  log "copying $src -> $DREMIO_HOME_DIR"
  cp -a "$src/." "$DREMIO_HOME_DIR/"
fi

mkdir -p "$DREMIO_HOME_DIR/data" "$DREMIO_HOME_DIR/log" "$DREMIO_HOME_DIR/run"
cat > "$DREMIO_HOME_DIR/conf/dremio.conf" <<CONF
# Generated by scripts/polaris-e2e/dremio-up.sh for INSTANCE=$INSTANCE
paths: {
  local: "$DREMIO_HOME_DIR/data"
  dist: "file://$DREMIO_HOME_DIR/data/pdfs"
}
services: {
  coordinator.enabled: true,
  coordinator.master.enabled: true,
  coordinator.master.embedded-zookeeper.port: $DREMIO_ZK_PORT,
  coordinator.web.port: $DREMIO_WEB_PORT,
  coordinator.web.ui.intercom.enabled: false,
  coordinator.client-endpoint.port: $DREMIO_CLIENT_PORT,
  executor.enabled: true,
  fabric.port: $DREMIO_FABRIC_PORT,
  flight.port: $DREMIO_FLIGHT_PORT,
  flight.use_session_service: true
}
CONF
cat > "$DREMIO_HOME_DIR/conf/dremio-env" <<ENVF
# Generated by scripts/polaris-e2e/dremio-up.sh for INSTANCE=$INSTANCE
JAVA_HOME="$DREMIO_JAVA_HOME"
DREMIO_LOG_DIR="$DREMIO_HOME_DIR/log"
DREMIO_PID_DIR="$DREMIO_HOME_DIR/run"
DREMIO_MAX_HEAP_MEMORY_SIZE_MB=$DREMIO_HEAP_MB
DREMIO_MAX_DIRECT_MEMORY_SIZE_MB=$DREMIO_DIRECT_MB
DREMIO_GC_LOGS_ENABLED="no"
ENVF

log "starting Dremio web=$DREMIO_WEB_PORT client=$DREMIO_CLIENT_PORT flight=$DREMIO_FLIGHT_PORT fabric=$DREMIO_FABRIC_PORT zk=$DREMIO_ZK_PORT"
# Start in a clean environment slice: S3/Polaris secrets are not needed by the Dremio process.
# Every AWS credential variable is removed, access key IDs included: Dremio's S3 file system falls
# back to AWS_ACCESS_KEY_ID/AWS_ACCESS_KEY + AWS_SECRET_ACCESS_KEY/AWS_SECRET_KEY when a source has
# no S3 credentials (empty provider), which would defeat the "no credentials" scenarios.
env -u S3_ACCESS_KEY -u S3_SECRET_KEY -u MINIO_SECRET_KEY -u POLARIS_ROOT_SECRET \
  -u AWS_ACCESS_KEY_ID -u AWS_ACCESS_KEY -u AWS_SECRET_ACCESS_KEY -u AWS_SECRET_KEY \
  -u AWS_SESSION_TOKEN -u AWS_PROFILE \
  JAVA_HOME="$DREMIO_JAVA_HOME" "$DREMIO_HOME_DIR/bin/dremio" start >/dev/null

web_up() { curl -sf --max-time 2 -o /dev/null "$DREMIO_URL/apiv2/server_status"; }
if ! wait_for "${DREMIO_START_TIMEOUT:-300}" "Dremio web" web_up; then
  tail -n 30 "$DREMIO_HOME_DIR/log/server.out" "$DREMIO_HOME_DIR/log/server.log" 2>/dev/null | redact >&2 || true
  die "Dremio did not come up on $DREMIO_URL"
fi

OUT="$WORK/.firstuser.json"
code="$(E2E_U="$DREMIO_USER" E2E_P="$DREMIO_PASSWORD" jq -n '{userName: env.E2E_U, firstName: "E2E", lastName: "Admin",
    email: "e2e@example.com", createdAt: (now * 1000 | floor), password: env.E2E_P}' |
  http PUT "$DREMIO_URL/apiv2/bootstrap/firstuser" "$OUT" <(printf 'Authorization: _dremionull\n') 1)"
rm -f "$OUT"
log "bootstrap first user $DREMIO_USER: HTTP $code"
dremio_login || die "login as $DREMIO_USER failed"
log "Dremio ready: $DREMIO_URL (token in $WORK/token)"
